#!/usr/local/bin/bash

export LANG=en_US.UTF-8

rm words
rm words-temp-1
rm words-temp-2

find . -iname "*tex" -and -not -iname "environment.tex" -exec ./collect-words-sub {} >> words-temp-1 \;

sort words-temp-1 | uniq | sort > words-temp-2

grep -v '^.\{1,4\}$' words-temp-2 > words
